<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="terms.aspx.cs" Inherits="Redemption.terms" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div id="main" role="main">
        <div class="container term_style">
            <div class="sixteen columns">
                <div class="title bg2">
                    <h4>Terms &amp; Conditions Of Use</h4>
                </div>
                <p>Welcome to Marshall Cavendish Education Rewards website. If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern Marshall Cavendish Education’s relationship with you in relation to this website.</p>
                <p><strong>The term</strong></p>
                <ol>
	                <li>The content of the pages of this website including the Terms and Conditions is subject to change without notice. All changes will be posted on this page, and your use of this site after such changes that have been posted will constitute your agreement to the modified Terms and Conditions.</li>
	                <li>In addition, particular services added or offered through this website may be subject to additional terms or guidelines, which shall be deemed incorporated in these Terms and Conditions by reference.</li>
	                <li>Your use of this website and any disputes arising in connection with the website, or any relevant terms and conditions, policies and notices or any matter related to or in connection therewith is subject to the laws of Singapore.</li>
	                <li>The information contained in this website is for general information purposes only and does not represent legal or other professional advice. Whilst we endeavour to keep the information up-to- date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability of the information contained on this website for any purpose whatsoever. Any reliance you place on such information is therefore strictly at your own risk. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements and to obtain legal and/or professional advice as necessary.</li>
	                <li>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Copyright in the contents and materials of this website as a whole is owned by Marshall Cavendish Education, though the copyright in some contents and materials incorporated within this website may be owned by third parties where so indicated. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions. Any unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.</li>
	                <li>From time to time this website may also include links to other websites. These links are provided for your convenience but they do not signify that we endorse the said websites. We have no control over the nature, content and availability of those sites. We shall not be liable for any damages or loss arising from your access to those websites. In no circumstances shall the owners and administrators of this site be associated or affiliated in whatever manner with any trade or service marks, logos, insignia or other devices used or appearing on websites to which this site is linked.</li>
	                <li>Members+ should post responsibly. The owners and administrators of this site shall not tolerate defamatory or libellous material, obscene content and abusive or intimidating comments. Unless otherwise stated, members+ may use content from the site as long as such content is attributed to the author of the post. Content (including, but not limited to, information, images, files, sounds and video clips contained on or available through this site) is provided by the owners and administrators of this site and its registered members+.</li>
	                <li>A Member+ owns all original content and information posted by the said Member+ on this website and can control how it is shared through the said Member's+ privacy and application settings. In addition, for content that is covered by intellectual property rights, like photos and videos (IP content), the said Member+ specifically gives Marshall Cavendish Education the following permission, subject to the Member's+ privacy and application settings:
		                <ol>
		                	<li><span>8.1. </span><p>You grant us a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use any IP content that you post on or in connection with this website (IP License). This IP License ends when you delete your IP content or your account unless your content has been shared with others, and they have not deleted it.</p></li>
		                	<li><span>8.2. </span><p>You will not assume a false identity or the identity of another user when using this website, and you will not this website for unlawful or illegal activities, including but not limited to spamming, harassing or otherwise causing distress to other users.</p></li>
		                	<li><span>8.3. </span><p>When you delete the IP content, it is deleted in a manner similar to emptying the recycle bin on a computer. However, you understand that removed content may persist in backup copies for a reasonable period of time (but will not be available to others).</p></li>
		                	<li><span>8.4. </span><p>When you add an application and use our website, your content and information is shared with the application. We require applications to respect your privacy settings, but your agreement with that application will control how the application can use the content and information you share.</p></li>
		                	<li><span>8.5. </span><p>When you publish content or information, it means that everyone will have access to that information and we may not have control over what they do with it.</p></li>
		                	<li><span>8.6. </span><p>We always appreciate your feedback or other suggestions about our website, but you understand that we may use them without any obligation to compensate you for them (just as you have no obligation to offer them).</p></li>
	                	</ol>
	                </li>
	                	
	                <li>You may link to <a href="http://edu.marshallcavendish.com/" target="_blank">http://www.marshallcavendish.com/education</a>. Please contact the site administrators for more information. Under no circumstances shall the owners and administrators of this site be considered to be associated or affiliated in whatever manner with any trade or service marks, logos, insignia or other devices used or appearing on websites that link to <a href="http://edu.marshallcavendish.com/" target="_blank">http://www.marshallcavendish.com/education</a> or any of the contents.</li>
	                <li>Marshall Cavendish Education reserves all rights to deny or restrict access to this site to any particular person, or to block access from a particular Internet address to this site, at any time, without ascribing any reasons whatsoever.</li>
	                <li>Marshall Cavendish Education is not responsible for any material submitted to the public areas by you (which include bulletin boards, hosted pages, chat rooms, or any other public area found on the website. Any material (whether submitted by you or any other user) is not endorsed, reviewed or approved by the Marshall Cavendish Education. Marshall Cavendish Education shall have the right (but not the obligation) at our sole discretion to pre-screen, refuse, move or remove any content that is available via the website. Without limiting the foregoing, Marshall Cavendish Education shall have the right to remove any content (whether or not provided by you) that we believe in good faith violates the terms and conditions for the use of Marshall Cavendish Education’s website or that has been alleged to infringe any intellectual property rights or that contains marketing or promotional material which is intended to solicit business or that is otherwise objectionable in our sole opinion, without being liable to you in any way for any loss or damage arising from such removal.</li>
	                <li>You further agree not to use the website to send or post any message or material that is unlawful, harassing, defamatory, abusive, indecent, threatening, harmful, vulgar, obscene, sexually orientated, racially offensive, profane, pornographic or violates any applicable law including any law relating to intellectual property rights, or to post or upload files that contain viruses, corrupted files or any other similar software or programmes that may damage the operation of Marshall Cavendish Education and/or a third party's computer system and/or network, and you hereby agree to fully indemnify Marshall Cavendish Education against any loss, liability, damage or expense of whatever nature which Marshall Cavendish Education or any third party may suffer which is caused by or attributable to, whether directly or indirectly, your use of the website to send or post or upload any such message or material.</li>
	                <li>Every effort is made to keep the website up and running smoothly. However, Marshall Cavendish Education takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.</li>
	                <li>On registration, you must provide Marshall Cavendish Education with complete and accurate information. Marshall Cavendish Education is entitled to rely on any registration information you provide unless and until such information is updated by you via this website.
</li>
	                <li>You agree that any personally identifiable information which you provide to us through this website may be collected by Marshall Cavendish Education and used for various purposes, including without limitation:
		                <ol>
		                	<li><span>15.1. </span><p>To provide goods and services by Marshall Cavendish Education or its designated representatives, related organisations or business partners to you or parties designated by you and matters ancillary thereto;</p></li>
		                	<li><span>15.2. </span><p>To verify and process payment when you purchase goods and services through this website;</p></li>
		                	<li><span>15.3. </span><p>To verify and record your personal particulars and to use the information to communicate with you;</p></li>
		                	<li><span>15.4. </span><p>To send you information, promotions and updates including marketing and advertising materials in relation to goods and services of Marshall Cavendish Education, its affiliates and related organisations;</p></li>
		                	<li><span>15.5. </span><p>To conduct statistical and other analysis of users of our website; and</p></li>
		                	<li><span>15.6. </span><p>To comply with any order of court or directive from authorities investigating any alleged offence, misdeeds and/or abuse or for the purpose of taking any legal action against any users for breach of these Terms and Conditions.</p></li>
	                	</ol>
	                </li>
	                	
	                <li>All receipts used for redemptions must be legible and accurate. All redemptions done through the website are subject to approval by Marshall Cavendish Education. Marshall Cavendish Education reserves the right to refuse any redemptions that are incomplete, expired or invalid.</li>
	                <li>All points are valid for a period of one year from the date of purchase only. All unutilised points will be forfeited and cannot be used in exchange for cash or any other items thereafter.</li>
	                <li>Marshall Cavendish Education and/or its affiliates or related organisations or content providers shall not be liable for any direct, indirect or consequential loss or damage of any kind occasioned from the reliance upon the contents contained in or available from this website, the performing of any transaction or communication on this website, and/or the use or inability to use this website, resulting from inaccuracies, neglect, defects, errors, omissions, out-dated information or otherwise.</li>
	                <li>The opinions expressed by individuals providing comments are theirs alone and may not necessarily reflect the opinions of the owners and administrators of this site. Marshall Cavendish Education therefore shall not be responsible for the accuracy of any of the information supplied by the users of the site in relation to any comments that are posted. You should bear in mind that circumstances change and that information that may have been accurate at the time of posting may not necessarily remain so. You agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Marshall Cavendish Education with respect thereto.</li>
	                <li>You agree not to circumvent, disable or otherwise interfere with security-related features of this website or features that prevent or restrict use or copying of any content or enforce limitations on use of this website or the content therein.</li>
	                <li>We respect the intellectual property of others, and we ask our users to do the same. If you believe that your intellectual property right has been infringed, please notify us at <a href="mailto:mcis_mktg@marshallcavendish.com.sg">mcis_mktg@marshallcavendish.com.sg</a>. Upon receipt of a complaint of infringement, we will expeditiously take reasonable steps to remove or disable access to the allegedly infringing electronic copy and expeditiously take reasonable steps to notify the person who had made that electronic copy available (Content Owner). We may also, in appropriate circumstances and at our sole discretion, disable and/or terminate without notice the accounts of users who may be infringing the intellectual property rights (including but not limited to copyrights and trademarks) of others. In particular, we will terminate the accounts of users whom we have determined (in our sole discretion) to be repeat infringers.</li>
                </ol>
                <p class="note">+Registered guest(s) of Marshall Cavendish Education website.</p>
            </div>
        </div>
        <!-- container -->
    </div>
</asp:Content>
